---
- name: Deploy web app
  hosts: n1
  become: yes

  tasks:
    - name: Install GIT
      yum:
        name: git
        state: present

    - name: Ensure /var/www/html directory exists
      file:
        path: /var/www/html
        state: directory

    - name: Host Code
      git:
        repo: https://github.com/CeeyIT-Solutions/ecomm-3.git
        dest: /var/www/html
...
