---
- name: Under Maintenance
  hosts: n2
  become: yes

  tasks:
    - name: Update maintenance
      copy:
        src: Maintenace.html
        dest: /var/www/html/index.html
        force: yes
... 